[tool.poetry]
name = "MicroEdit"
version = "1.0.0"
description = "A non-interactive file editor"
authors = ["Kokonico <kokonico@duck.com>"]
scripts = { medit = "microedit.main:main" }
license = "Zlib"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
objlog = "3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
